---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  format: doc 

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[bwa::default]
    attributes:
