name 'bwa'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'apachev2'
description 'Installs/Configures bwa'
long_description 'Installs/Configures bwa'
source_url 'https://github.com/EagleGenomics-cookbooks/bwa'
issues_url 'https://github.com/EagleGenomics-cookbooks/bwa/issues'
version '1.0.0'

depends 'apt'
depends 'build-essential'
